USE shrimpedin;
CREATE TABLE IF NOT EXISTS `shrimpedin`user table``.`User Table` (
  `ID` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `f_name` NVARCHAR(50) NOT NULL,
  `m_name` NVARCHAR(50) NULL,
  `l_name` NVARCHAR(50) NOT NULL,
  `password` BINARY(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `User_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;