USE shrimpedin;
CREATE TABLE IF NOT EXISTS user_table(
  `ID` INT ZEROFILL NOT NULL AUTO_INCREMENT,
  `username` INT NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `User_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;